### ISSUE TITLE
Add soundcloud music search

### ISSUE THREAD

**Issue by Legedith** [Legedith/Sirius#15]

**Comment by gunjanraval** [comment]
Do you want to reply with the first link of the search result?

**Comment by Legedith** [comment]
Yes, even the search url would do. But you can add an optional feature that would download and then send the requested song.

**Comment by gunjanraval** [comment]
Ok! I'll first try the URL part!

**Comment by gunjanraval** [comment]
Do you have a specific name(spell) for the feature? I was thinking CANTIS, in relation to this : https://harrypotter.fandom.com/wiki/Cantis
